### ISSUE TITLE
Segfault trying to serialize a `json_object`

### ISSUE THREAD

**Issue by minhqdao** [toml-f/jonquil#13]
When I try to serialize a `json_object` using `json_serialize`, I observe a `Segmentation fault`:

```fortran
program main
  use jonquil

  implicit none

  type(json_object) :: object

  call set_value(object, "val", 1.0)

  print *, json_serialize(object)

end program
```
```bash
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
```

Adding `call new_object(object)` before `set_value` solves the issue.

I think that either:

1) `set_value` should automatically initialize a new object if is wan't initialized or
2) an error should be thrown informing the user that the object wasn't initialized before usage.

I'd prefer 1), though.

macOS/ARM, gfortran, fpm version 0.7.0

**Comment by awvwgk** [comment]
All objects in TOML Fortran and Jonquil need to be initialized, the easiest way to do is:

````f90
block
  use jonquil, only : json_object
  type(json_object) :: object
  object = json_object()
end block
````

**Comment by minhqdao** [comment]
Alright, I'd prefer 2) if they need to be manually initialized then.

**Comment by awvwgk** [comment]
Creating an error seems to require the same effort as initializing the data structures, i.e. checking whether the storage structure in the object is allocated. Therefore, I went with solution 1 in https://github.com/toml-f/toml-f/pull/130.

Still, I would recommend to initialize data structures manually rather than relying on the build interface doing it implicitly.

**Comment by awvwgk** [comment]
Well, the relevant implementation is part of TOML Fortran rather than Jonquil. But I will create patch releases for both to include the fix.
